USE AIRSAFE_BATTERY_SERVICE;

CREATE TABLE IF NOT EXISTS USER (
	USER_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    HASHED_PASSWORD VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMIN (
	ADMIN_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    HASHED_PASSWORD VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
	PAYMENT_ID VARCHAR(10) PRIMARY KEY,
    PAYMENT_TIMESTAMP TIMESTAMP NOT NULL,
    PAYMENT_AMOUNT DECIMAL(8, 2) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);

CREATE TABLE IF NOT EXISTS POWERBANKRULE (
	RULE_ID VARCHAR(10) PRIMARY KEY,
    MAX_CARRY INT,
    MAX_WH INT,
    CHECKED_BAGGAGE BOOLEAN NOT NULL,
    CARRY_ON_BAGGAGE BOOLEAN NOT NULL,
    REFERENCE VARCHAR(8000) NOT NULL
);

-- DROP TABLE IF EXISTS CHECKHISTORY;

CREATE TABLE IF NOT EXISTS CHECKHISTORY (
	CHECK_ID VARCHAR(10) PRIMARY KEY,
    CHECK_TIMESTAMP TIMESTAMP NOT NULL,
    CHECK_STATUS ENUM('Approved', 'Not Approved') NOT NULL,
    CAPACITY DECIMAL(8, 2),
    WH DECIMAL(5, 2) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    RULE_ID VARCHAR(10) NOT NULL,
    CONSTRAINT FK_CHECK_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_CHECK_RULE FOREIGN KEY (RULE_ID) REFERENCES POWERBANKRULE(RULE_ID)
);

-- DROP TABLE IF EXISTS POWERBANKINPUT;
-- DROP TABLE IF EXISTS POWERBANKOUTPUT;
-- DROP TABLE IF EXISTS POWERBANK;

CREATE TABLE IF NOT EXISTS POWERBANK(
	BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    CAPACITY DECIMAL(8, 2),
    WH DECIMAL(5, 2) NOT NULL,
    WIDTH DECIMAL(5, 2) NOT NULL,
    LENGTH DECIMAL(5, 2) NOT NULL,
    HEIGHT DECIMAL(5, 2) NOT NULL,
    WEIGHT DECIMAL(5, 2) NOT NULL,
    IMAGE BLOB,
    
    PRIMARY KEY (BRAND, NAME, MODEL)
);

-- DROP TABLE IF EXISTS DEPOSITEDPOWERBANK;

CREATE TABLE IF NOT EXISTS DEPOSITEDPOWERBANK(
	BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    CAPACITY DECIMAL(8, 2),
    WH DECIMAL(5, 2) NOT NULL,
    WIDTH DECIMAL(5, 2) NOT NULL,
    LENGTH DECIMAL(5, 2) NOT NULL,
    HEIGHT DECIMAL(5, 2) NOT NULL,
    WEIGHT DECIMAL(5, 2) NOT NULL,
    IMAGE BLOB,
    
    DEPOSIT_STATUS ENUM('Locker Reserved', 'Is being deposited', 'Late') NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    DEPOSIT_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    LOCKER_NUMBER INT NOT NULL,
    LATE_FEE_PER_DAY DECIMAL(4, 2) NOT NULL,
    DEPOSIT_PRICE DECIMAL(6, 2) NOT NULL,
    HASHED_LOCKER_PASSWORD VARCHAR(150) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    PAYMENT_ID VARCHAR(10) NOT NULL,
    
    PRIMARY KEY (BRAND, NAME, MODEL),
    CONSTRAINT FK_DEPOSIT_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_DEPOSIT_TRANSACTION FOREIGN KEY (PAYMENT_ID) REFERENCES TRANSACTION(PAYMENT_ID)
);

-- DROP TABLE IF EXISTS RENTEDPOWERBANK;

CREATE TABLE IF NOT EXISTS RENTEDPOWERBANK(
	BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    CAPACITY DECIMAL(8, 2),
    WH DECIMAL(5, 2) NOT NULL,
    WIDTH DECIMAL(5, 2) NOT NULL,
    LENGTH DECIMAL(5, 2) NOT NULL,
    HEIGHT DECIMAL(5, 2) NOT NULL,
    WEIGHT DECIMAL(5, 2) NOT NULL,
    IMAGE BLOB,
    
    HASHED_LOCKER_PASSWORD VARCHAR(150) NOT NULL,
    RETURN_ADDRESS VARCHAR(100) NOT NULL,
    PICK_UP_ADDRESS VARCHAR(100) NOT NULL,
    PICK_UP_DATE DATE NOT NULL,
    RENT_STATUS ENUM('Not taken', 'Activated', 'Late') NOT NULL,
    RETURN_DATE DATE NOT NULL,
    LATE_FEE_PER_DAY DECIMAL(4, 2) NOT NULL,
    RENT_PRICE DECIMAL(6, 2) NOT NULL,
    LOCKER_NUMBER INT NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    PAYMENT_ID VARCHAR(10) NOT NULL,
    
    PRIMARY KEY (BRAND, NAME, MODEL),
    CONSTRAINT FK_RENT_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_RENT_TRANSACTION FOREIGN KEY (PAYMENT_ID) REFERENCES TRANSACTION(PAYMENT_ID)
);

-- DROP TABLE IF EXISTS FORRENTPOWERBANK;

CREATE TABLE IF NOT EXISTS FORRENTPOWERBANK(
	BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    CAPACITY DECIMAL(8, 2),
    WH DECIMAL(5, 2) NOT NULL,
    WIDTH DECIMAL(5, 2) NOT NULL,
    LENGTH DECIMAL(5, 2) NOT NULL,
    HEIGHT DECIMAL(5, 2) NOT NULL,
    WEIGHT DECIMAL(5, 2) NOT NULL,
    IMAGE BLOB,
    
    ADDRESS VARCHAR(100) NOT NULL,
    LOCKER_NUMBER INT NOT NULL,
    LATE_FEE_PER_DAY DECIMAL(4, 2) NOT NULL,
    PRICE_PER_DAY DECIMAL(6, 2) NOT NULL,
    MAX_DURATION INT NOT NULL,
    
    PRIMARY KEY (BRAND, NAME, MODEL)
);

CREATE TABLE IF NOT EXISTS POWERBANKINPUT(
	INPUT_TYPE VARCHAR(80) NOT NULL,
    BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (INPUT_TYPE, BRAND, NAME, MODEL),
    CONSTRAINT FK_INPUT_POWERBANK FOREIGN KEY (BRAND, NAME, MODEL) REFERENCES POWERBANK (BRAND, NAME, MODEL)
);

CREATE TABLE IF NOT EXISTS POWERBANKOUTPUT(
	OUTPUT_TYPE VARCHAR(80) NOT NULL,
    BRAND VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    MODEL VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (OUTPUT_TYPE, BRAND, NAME, MODEL),
    CONSTRAINT FK_OUTPUT_POWERBANK FOREIGN KEY (BRAND, NAME, MODEL) REFERENCES POWERBANK (BRAND, NAME, MODEL)
);

SHOW TABLES;








