USE AIRSAFE_BATTERY_SERVICE;

CREATE TABLE IF NOT EXISTS USER (
	USER_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    HASHED_PASSWORD VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS ADMIN (
	ADMIN_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    HASHED_PASSWORD VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS TRANSACTION (
	PAYMENT_ID VARCHAR(10) PRIMARY KEY,
    PAYMENT_TIMESTAMP TIMESTAMP NOT NULL,
    PAYMENT_AMOUNT DECIMAL(8, 2) NOT NULL,
    USER_ID VARCHAR(10) NOT NULL,
    CONSTRAINT FK_USER FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);












